openapi: 3.0.1
info:
  title: Hello Queryparams API
  description: Public API for Testing openApi/Swagger with Micronaut and Query Parameters
  version: "1.0"
servers:
- url: https://example.com
tags:
- name: /hello
paths:
  /hello{?foo,bar}:
    get:
      tags:
      - /hello
      operationId: query
      parameters:
      - name: foo
        in: path
        required: true
        schema:
          type: string
          nullable: true
      - name: bar
        in: path
        required: true
        schema:
          type: string
          nullable: true
      responses:
        default:
          content:
            text/plain:
              schema:
                type: string
